"""Make certain fields nullable in Doctor and Patient models

Revision ID: babf7c363a48
Revises: d77af934eb7b
Create Date: 2025-04-04 21:01:45.976478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'babf7c363a48'
down_revision = 'd77af934eb7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.alter_column('specialization',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.alter_column('doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('disease_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('disease_image',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('disease_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('disease_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('disease_image',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('disease_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('email')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('specialization',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
