"""Initial migration

Revision ID: d77af934eb7b
Revises: 
Create Date: 2025-04-04 13:41:42.378529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77af934eb7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint('fk_doctor', type_='foreignkey')
        batch_op.create_foreign_key(None, 'doctor', ['doctor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_doctor', 'doctor', ['doctor_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
